function [] = createMaterialDirect()
%CREATEMATERIALDIRECT
%   Creates material .mat file directly (no GUI)
%
%   Reference section in Quick Fatigue Tool User Guide
%      5 Materials
%
%   Quick Fatigue Tool 6.11-13 Copyright Louis Vallance 2018
%   Last modified 07-Mar-2018 07:50:12 GMT

%% Material name
materialName = 'Steel';

%% Add material data
material_properties = struct(...
'default_algorithm', 7.0,...
'default_msc', 4.0,...
'class', 1.0,...
'behavior', 1.0,...
'reg_model', 1.0,...
'cael', 1e7,...
'cael_active', 0.0,...
'ndCompression', 0.0,...
'e', [],...
'e_active', 0.0,...
'uts', [],...
'ucs', [],...
'uts_active', 0.0,...
'proof', [],...
'proof_active', 0.0,...
'poisson', 0.33,...
'poisson_active', 0.0,...
's_values', [],...
'n_values', [],...
'r_values', [],...
'sf', [],...
'sf_active', 0.0,...
'b', [],...
'b_active', 0.0,...
'b2', [],...
'b2Nf', [],...
'ef', [],...
'ef_active', 0.0,...
'c', [],...
'c_active', 0.0,...
'kp', [],...
'kp_active', 0.0,...
'np', [],...
'np_active', 0.0,...
'nssc', 0.2857,...
'nssc_active', 0.0,...
'comment', [],...
'failStress_tsfd', [],...
'failStress_csfd', [],...
'failStress_tstd', [],...
'failStress_cstd', [],...
'failStress_tsttd', [],...
'failStress_csttd', [],...
'failStress_shear', [],...
'failStress_cross12', 0.0,...
'failStress_cross23', 0.0,...
'failStress_limit12', [],...
'failStress_limit23', [],...
'failStrain_tsfd', [],...
'failStrain_csfd', [],...
'failStrain_tstd', [],...
'failStrain_cstd', [],...
'failStrain_shear', [],...
'failStrain_e11', [],...
'failStrain_e22', [],...
'failStrain_g12', [],...
'hashin_alpha', 0.0,...
'hashin_lts', [],...
'hashin_lcs', [],...
'hashin_tts', [],...
'hashin_tcs', [],...
'hashin_lss', [],...
'hashin_tss', [],...
'larc05_lts', [],...
'larc05_lcs', [],...
'larc05_tts', [],...
'larc05_tcs', [],...
'larc05_lss', [],...
'larc05_tss', [],...
'larc05_shear', [],...
'larc05_nl', [],...
'larc05_nt', [],...
'larc05_alpha0', 53.0,...
'larc05_phi0', 0.0,...
'larc05_iterate', 0.0); %#ok<NASGU>

%% Save the material
save([pwd, '\Data\material\local\', materialName, '.mat'], 'material_properties')